Repository alainseys/ad_createcsv, pull requests merged in 2020-10, with the labels that each got.

#1 logging-module
  Cns_CreateCsv/.gitignore
  Cns_CreateCsv/App.config
  Cns_CreateCsv/Cns_CreateCsv.csproj
  Cns_CreateCsv/Cns_CreateCsv.sln
  Cns_CreateCsv/Program.cs
  Cns_CreateCsv/Properties/AssemblyInfo.cs
  Cns_CreateCsv/obj/Debug/.NETFramework,Version=v4.7.2.AssemblyAttributes.cs
  Cns_CreateCsv/obj/Debug/Cns_CreateCsv.csproj.CopyComplete
  Cns_CreateCsv/obj/Debug/Cns_CreateCsv.csproj.CoreCompileInputs.cache
  Cns_CreateCsv/obj/Debug/Cns_CreateCsv.csproj.FileListAbsolute.txt
  Cns_CreateCsv/obj/Debug/Cns_CreateCsv.csprojAssemblyReference.cache
  Cns_CreateCsv/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
  Cns_CreateCsv/packages.config
  Cns_CreateCsv/packages/log4net.2.0.11/.signature.p7s
  Cns_CreateCsv/packages/log4net.2.0.11/lib/net20/log4net.xml
  Cns_CreateCsv/packages/log4net.2.0.11/lib/net35-client/log4net.xml
  Cns_CreateCsv/packages/log4net.2.0.11/lib/net35/log4net.xml
  Cns_CreateCsv/packages/log4net.2.0.11/lib/net40-client/log4net.xml
  Cns_CreateCsv/packages/log4net.2.0.11/lib/net40/log4net.xml
  Cns_CreateCsv/packages/log4net.2.0.11/lib/net45/log4net.xml
  Cns_CreateCsv/packages/log4net.2.0.11/lib/netstandard1.3/log4net.xml
  Cns_CreateCsv/packages/log4net.2.0.11/lib/netstandard2.0/log4net.xml
  Cns_CreateCsv/packages/log4net.2.0.11/log4net.2.0.11.nupkg
  Cns_CreateCsv/packages/log4net.2.0.11/package-icon.png
Labels: hacktoberfest

#7 modification for the class file of the csv import
  Cns_CreateCsv/Program.cs
Labels: hacktoberfest

#8 changed filename to datetime executed program
  Cns_CreateCsv/Program.cs
Labels: enhancement, hacktoberfest

#10 Update Program.cs
  Cns_CreateCsv/Program.cs
Labels: hacktoberfest-accepted
